name: Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Ternuino CPU Simulator ${{ github.ref }}
        body: |
          ## Ternuino CPU Simulator Release
          
          This release includes compiled binaries for Windows, Linux, and macOS.
          
          ### What's New
          - High-performance C implementation of the Ternuino CPU simulator
          - Full compatibility with existing assembly programs
          - Cross-platform support (Windows, Linux, macOS)
          - Interactive and command-line modes
          
          ### Downloads
          - **Windows**: `ternuino-windows.exe` - Requires no additional dependencies
          - **Linux**: `ternuino-linux` - Compiled for x86_64 Linux systems
          - **macOS**: `ternuino-macos` - Universal binary for Intel and Apple Silicon
          
          ### Usage
          ```bash
          # Run specific program
          ./ternuino programs/fibonacci_demo.asm
          
          # Interactive mode
          ./ternuino
          ```
          
          ### Assembly Programs Included
          - `arithmetic_demo.asm` - Basic arithmetic operations
          - `fibonacci_demo.asm` - Fibonacci sequence calculation
          - `logic_demo.asm` - Ternary logic operations
          - `loop_demo.asm` - Control flow examples
          - `memory_demo.asm` - Memory operations
          - And more...
          
          For full documentation, see the README.md file.
        draft: false
        prerelease: false

  build-and-upload:
    name: Build and Upload ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux
            artifact: ternuino-linux
            executable: ternuino
          - os: windows-latest
            name: Windows  
            artifact: ternuino-windows.exe
            executable: ternuino.exe
          - os: macos-latest
            name: macOS
            artifact: ternuino-macos
            executable: ternuino
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Build Environment (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make
        
    - name: Setup Build Environment (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        gcc --version
        
    - name: Setup Build Environment (Windows)
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          make
          
    - name: Build (Linux/macOS)
      if: matrix.os != 'windows-latest'
      working-directory: src
      run: |
        make clean || true
        make
        
    - name: Build (Windows)
      if: matrix.os == 'windows-latest'
      working-directory: src
      shell: msys2 {0}
      run: |
        export PATH="/mingw64/bin:$PATH"
        gcc --version
        
        # Use our GitHub Actions build script which doesn't require make
        echo "Building with GitHub Actions script..."
        cmd //c build-github.bat
        
    - name: Test executable
      working-directory: src
      shell: bash
      run: |
        if [ -f "build/${{ matrix.executable }}" ]; then
          echo "✅ Executable built successfully: build/${{ matrix.executable }}"
          ls -la "build/${{ matrix.executable }}"
        else
          echo "❌ Executable not found!"
          exit 1
        fi
        
    - name: Create release package
      working-directory: src
      shell: bash
      run: |
        mkdir -p release-package
        cp "build/${{ matrix.executable }}" "release-package/"
        cp -r programs release-package/
        cp README.md release-package/ 2>/dev/null || echo "README.md not found in src, skipping"
        
        # Create a simple usage instructions file
        cat > release-package/USAGE.txt << 'EOF'
        Ternuino CPU Simulator - Usage Instructions
        
        1. Interactive Mode:
           Run the executable without arguments to see available programs
           and select one interactively.
           
        2. Command Line Mode:
           Run with a specific .asm file:
           ./${{ matrix.executable }} programs/fibonacci_demo.asm
           
        3. Available Programs:
           - arithmetic_demo.asm - Basic arithmetic operations
           - fibonacci_demo.asm - Fibonacci sequence
           - logic_demo.asm - Ternary logic operations
           - loop_demo.asm - Control flow examples
           - memory_demo.asm - Memory operations
           - And more...
           
        For more information, visit:
        https://github.com/${{ github.repository }}
        EOF
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: src/build/${{ matrix.executable }}
        asset_name: ${{ matrix.artifact }}
        asset_content_type: application/octet-stream
